In [6]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
addition=A+B
print("Addidtion:\n",addition)
subtraction=A-B
print("\nSubtraction=\n",subtraction)
multiplication=A*B
print("\nMutliplication=\n",multiplication)
division=A/B
print("\nDivision=\n",division)
dot_pro=np.dot(A,B)
print("\nDot product:\n",dot_pro)
trans_A=A.T
print("\nTranspose of A:\n",trans_A)
trans_B=B.T
print("\nTranspose of B:\n",trans_B)


Addidtion:
 [[ 6  8]
 [10 12]]

Subtraction=
 [[-4 -4]
 [-4 -4]]

Mutliplication=
 [[ 5 12]
 [21 32]]

Division=
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

Dot product:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Transpose of B:
 [[5 7]
 [6 8]]
