In [2]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_comp=2
X_recons=np.dot(U[:,:n_comp],np.dot(np.diag(S[:n_comp]),VT[:n_comp,:]))
print("original Matrix:")
print(X)
print("\nReconstructed Matrix(with reduced dimensions):")
print(X_recons)

original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
